services:
    hartwig_image_magick.twig.image_extension:
        class: Hartwig\Bundle\ImageMagickBundle\Twig\ImageExtension
        arguments: [ "@service_container" ]
        tags:
            - { name: twig.extension }